# Spectral GAN training configuration

structure:
  N_layers: 16
  pol: 0
  thickness_sup: 0.2
  thickness_bot: 0.05

materials:
  materials_list:
    - Ge
    - SiO2

optics:
  wavelength_range: [3, 5.5]
  samples_total: 5000
  theta: 0.0
  n_top: 1.0
  n_bot: 1.0
  lorentz_width: 0.005
  lorentz_center_range: [4, 4.5]
  metal_name: "Au"

generator:
  thickness_noise_dim: 1024
  material_noise_dim: 1024
  alpha_sup: 4
  alpha: 200

training:
  epochs: 300
  batch_size: 256
  save_interval: 10
  noise_level: 0.005
  lambda_gp: 3.0
  d_steps: 1
  g_steps: 2

optimizer:
  lr_gen: 0.001
  lr_disc: 0.0001
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0001
